# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Treasure' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Treasure
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  target 'TreasureTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
